/** Compatibility facade for deterministic profile contracts and evaluators. */
export {
  RIDDLE_PROOF_HOSTED_PROFILE_ARTIFACTS,
  RIDDLE_PROOF_ORDERED_TRACE_OPERATORS,
  RIDDLE_PROOF_PROFILE_CHECK_TYPES,
  RIDDLE_PROOF_PROFILE_EVIDENCE_VERSION,
  RIDDLE_PROOF_PROFILE_NETWORK_ABORT_ERROR_CODES,
  RIDDLE_PROOF_PROFILE_RESULT_VERSION,
  RIDDLE_PROOF_PROFILE_SETUP_ACTION_TYPES,
  RIDDLE_PROOF_PROFILE_STATUSES,
  RIDDLE_PROOF_PROFILE_VERSION,
  applyRiddleProofProfileArtifactCompleteness,
  assessRiddleProofOrderedTrace,
  assessRiddleProofOrderedTraceSetupResults,
  assessRiddleProofProfileArtifactCompleteness,
  assessRiddleProofProfileEvidence,
  collectRiddleProfileArtifactRefs,
  collectRiddleProofProfileWarnings,
  createRiddleProofProfileConfigurationError,
  createRiddleProofProfileEnvironmentBlockedResult,
  createRiddleProofProfileInsufficientResult,
  deriveRiddleProofArtifactBodyAssertions,
  extractRiddleProofProfileResult,
  normalizeRiddleProofProfile,
  preflightRiddleProofProfileRunnerArtifacts,
  profileStatusExitCode,
  resolveRiddleProofProfileRouteUrl,
  resolveRiddleProofProfileTargetUrl,
  resolveRiddleProofProfileTimeoutSec,
  slugifyRiddleProofProfileName,
  summarizeRiddleProofProfileResult,
} from "@riddledc/riddle-proof-core/profile";

export type {
  NormalizeRiddleProofProfileOptions,
  RiddleProofArtifactBodyAssertionInput,
  RiddleProofArtifactBodyAssertionResult,
  RiddleProofOrderedTraceAssessment,
  RiddleProofOrderedTraceEvent,
  RiddleProofOrderedTraceOperator,
  RiddleProofOrderedTracePredicate,
  RiddleProofOrderedTraceWitness,
  RiddleProofProfile,
  RiddleProofProfileArtifactCompleteness,
  RiddleProofProfileArtifactRef,
  RiddleProofProfileBaselinePolicy,
  RiddleProofProfileBoundsOffender,
  RiddleProofProfileCheck,
  RiddleProofProfileCheckResult,
  RiddleProofProfileCheckType,
  RiddleProofProfileEvidence,
  RiddleProofProfileFailureAction,
  RiddleProofProfileHttpStatusBodyJsonAssertion,
  RiddleProofProfileHttpStatusBodyJsonAssertionResult,
  RiddleProofProfileHttpStatusPreflightCheckResult,
  RiddleProofProfileHttpStatusPreflightFetch,
  RiddleProofProfileHttpStatusPreflightFetchResponse,
  RiddleProofProfileHttpStatusPreflightOptions,
  RiddleProofProfileHttpStatusPreflightResult,
  RiddleProofProfileJsonValueType,
  RiddleProofProfileNetworkAbortErrorCode,
  RiddleProofProfileNetworkMock,
  RiddleProofProfileNetworkMockResponse,
  RiddleProofProfileResult,
  RiddleProofProfileReturnSummaryField,
  RiddleProofProfileRouteEvidence,
  RiddleProofProfileRouteInventoryRoute,
  RiddleProofProfileRunner,
  RiddleProofProfileRunnerArtifactPreflight,
  RiddleProofProfileSetupAction,
  RiddleProofProfileSetupActionType,
  RiddleProofProfileStatus,
  RiddleProofProfileTarget,
  RiddleProofProfileViewport,
  RiddleProofProfileViewportEvidence,
} from "@riddledc/riddle-proof-core/profile";

/** Capability-bearing compatibility operations remain outside the offline core. */
export {
  buildRiddleProofProfileScript,
  preflightRiddleProofProfileHttpStatusChecks,
} from "./profile-capabilities";
